services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      ENABLE_AUTOPAUSE: "true"
      MAX_TICK_TIME: -1
      PACKWIZ_URL: "https://raw.githubusercontent.com/AChardonnet/skyblock/refs/heads/master/pack.toml"
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - minecraft-network
    volumes:
      - ./minecraft-data:/data

networks:
  minecraft-network:
    external: true
    driver: bridge